/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thelp.desktop;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JFrame;

/**
 *
 * @author kaka2
 */
public abstract class BaseForm extends javax.swing.JFrame 

{
    private static final int BASE_WIDTH = 1366;
    private static final int BASE_HEIGHT = 768;

    private double scaleX;
    private double scaleY;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BaseForm.class.getName());

    /**
     * Creates new form BaseForm
     */
    public BaseForm(String title) 
    {
        
        setTitle(title);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        
        scaleX = (double) screenWidth / BASE_WIDTH;
        scaleY = (double) screenHeight / BASE_HEIGHT;
        
        int frameWidth = (int) (BASE_WIDTH * scaleX * 0.9);
        int frameHeight = (int) (BASE_HEIGHT * scaleY * 0.9);
        setSize(frameWidth, frameHeight);
        setLocationRelativeTo(null);
        //setVisible(true);
        
        addComponentListener(new ComponentAdapter() 
        {
            @Override
            public void componentShown(ComponentEvent e) {
                ajustarComponentes(getContentPane());
            }
            @Override
            public void componentResized(ComponentEvent e) 
                {
                ajustarComponentes(getContentPane());
            }  
            });
  }
    
    private void ajustarComponentes(Container container) {
        for (Component c : container.getComponents()) {

            // Ajusta o tamanho preferido proporcionalmente à tela
            Dimension preferred = c.getPreferredSize();
            if (preferred != null) {
                int newWidth = (int) (preferred.width * scaleX);
                int newHeight = (int) (preferred.height * scaleY);
                c.setPreferredSize(new Dimension(newWidth, newHeight));
            }

            // Ajusta fonte proporcionalmente (opcional, mas deixa visual uniforme)
            Font f = c.getFont();
            if (f != null) {
                float newSize = (float) (f.getSize2D() * Math.min(scaleX, scaleY));
                c.setFont(f.deriveFont(newSize));
            }

            if (c instanceof Container) {
                ajustarComponentes((Container) c);
            }
        }

        container.revalidate();
        container.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
