/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package thelp.desktop;

import thelp.desktop.Database.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kaka2
 */
public class Dashboard extends javax.swing.JPanel {

    // Cores do tema
  //  private final Color PRIMARY_COLOR = new Color(41, 128, 185);
    //private final Color SUCCESS_COLOR = new Color(39, 174, 96);
    //private final Color WARNING_COLOR = new Color(243, 156, 18);
    //private final Color DANGER_COLOR = new Color(231, 76, 60);
    //private final Color CARD_BG = new Color(255, 255, 255);
    //private final Color PANEL_BG = new Color(245, 245, 245);
    
    /**
     * Creates new form Dashboard
     */
   public Dashboard() {
        //setTitle("THelp - Desktop");
        //createDashboard();
        initComponents();
        carregarDadosDashboard();
        
    }
   private int contarChamados(String status) 
   {
    String sql = "SELECT COUNT(*) FROM chamado WHERE cha_status = ?";

    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, status);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            return rs.getInt(1);
        }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return 0;
    }
   private void carregarChamadosRecentes() 
   {
       String sql = "SELECT id_chamado, cha_titulo, cha_status FROM chamado ORDER BY id_chamado DESC LIMIT 20";

        DefaultTableModel model = (DefaultTableModel) tblChamados.getModel();
        model.setRowCount(0); // limpa tabela

        try (Connection conn = DatabaseConnection.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_chamado"),
                rs.getString("cha_titulo"),
                rs.getString("cha_status")
            });
        }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
   private void carregarDadosDashboard() {

    // Atualiza Cards
    lblValor1.setText(String.valueOf(contarChamados("aberto")));
    lblValor2.setText(String.valueOf(contarChamados("fechado")));
    lblValor3.setText(String.valueOf(contarChamados("em_andamento")));

    // Atualiza tabela
    carregarChamadosRecentes();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlCardAbertos = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        pnlCardFechados = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        pnlCardPendentes = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        lblValor3 = new javax.swing.JLabel();
        pnlChart = new javax.swing.JPanel();
        lblChartgrafico = new javax.swing.JLabel();
        pnlTabela = new javax.swing.JPanel();
        lblTitulorecente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamados = new javax.swing.JTable();

        setBackground(new java.awt.Color(15, 23, 42));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setBackground(new java.awt.Color(245, 245, 245));
        pnlMain.setPreferredSize(new java.awt.Dimension(280, 280));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(51, 51, 51));
        lblTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblTitulo.setText("Dashboard");
        pnlMain.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(221, 221, 221));
        pnlMain.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 900, 2));

        pnlCardAbertos.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardAbertos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        pnlCardAbertos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTitulo1.setText("Chamados abertos");
        pnlCardAbertos.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

        lblValor1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        lblValor1.setForeground(new java.awt.Color(74, 144, 226));
        lblValor1.setText("12");
        pnlCardAbertos.add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, -1, -1));

        pnlMain.add(pnlCardAbertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 120));

        pnlCardFechados.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardFechados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        pnlCardFechados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTitulo2.setText("Chamados Fechados");
        pnlCardFechados.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

        lblValor2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        lblValor2.setForeground(new java.awt.Color(74, 144, 226));
        lblValor2.setText("12");
        pnlCardFechados.add(lblValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, -1, -1));

        pnlMain.add(pnlCardFechados, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 200, 120));

        pnlCardPendentes.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardPendentes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        pnlCardPendentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTitulo3.setText("Chamados Pendentes");
        pnlCardPendentes.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

        lblValor3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        lblValor3.setForeground(new java.awt.Color(74, 144, 226));
        lblValor3.setText("12");
        pnlCardPendentes.add(lblValor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, -1, -1));

        pnlMain.add(pnlCardPendentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 200, 120));

        pnlChart.setBackground(new java.awt.Color(255, 255, 255));
        pnlChart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));

        lblChartgrafico.setBackground(new java.awt.Color(153, 153, 153));
        lblChartgrafico.setText("Gráfico aparecerá aqui");

        javax.swing.GroupLayout pnlChartLayout = new javax.swing.GroupLayout(pnlChart);
        pnlChart.setLayout(pnlChartLayout);
        pnlChartLayout.setHorizontalGroup(
            pnlChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChartLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(lblChartgrafico)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        pnlChartLayout.setVerticalGroup(
            pnlChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChartLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(lblChartgrafico)
                .addGap(135, 135, 135))
        );

        pnlMain.add(pnlChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 550, 300));

        pnlTabela.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        pnlTabela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulorecente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulorecente.setText("Chamados Recentes");
        pnlTabela.add(lblTitulorecente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setColumnHeaderView(null);
        jScrollPane1.setName(""); // NOI18N

        tblChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblChamados);

        pnlTabela.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 240));

        pnlMain.add(pnlTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 350, 300));

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 580));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblChartgrafico;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulorecente;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JPanel pnlCardAbertos;
    private javax.swing.JPanel pnlCardFechados;
    private javax.swing.JPanel pnlCardPendentes;
    private javax.swing.JPanel pnlChart;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTabela;
    private javax.swing.JTable tblChamados;
    // End of variables declaration//GEN-END:variables
}
